version: '3.9'
services:
  chat-db:
    image: postgres:15-alpine
    container_name: chat-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES__DATABASE}
      POSTGRES_USER: ${POSTGRES__USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  mongo-db:
    image: mongo:6.0
    container_name: chat-mongo
    env_file:
      - .env
    environment:
      MONGO__DATABASE: ${MONGO__DATABASE}
      MONGO__USERNAME: ${MONGO__USERNAME}
      MONGO__PASSWORD: ${MONGO__PASSWORD}
    command: ["mongod", "--replSet", "rs0"]
    volumes: 
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: 
      context: .
      target: development
    container_name: chat-backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES__USERNAME}:${POSTGRES__PASSWORD}@chat-db:5432/${POSTGRES__DATABASE}
      - MONGO_URL=mongodb://${MONGO__USERNAME}:${MONGO__PASSWORD}@mongo-db:27017/${MONGO__DATABASE}
    ports:
      - "8000:8000"
    depends_on:
      - chat-db
      - mongo-db
    volumes:
      - .:/app

volumes:
  postgres_data:
  mongo_data: